### PR TITLE
port to QGIS3

### PR DESCRIPTION
**Pull request by AlisterH**
Port to QGIS3; it could be cleaned up a little.

### CODE REVIEW

**Comment by mdouchin** [comment]
Thanks a lot @AlisterH for your work. Please ping us when you decide we should merge your PR.

**Comment by AlisterH** [comment]
Hi, I would merge it now.  It seems to be all working on 3.x, the only issue is that when outputting to printer the text is vectorised (not rasterised as I mistakenly said in a commit message).  This must be a problem with Qt5 or QtWebkit; I tried to look into it, but didn't get anywhere.
It would need more work if you wanted it to still work in 2.x, otherwise ideally all the code that was to support older versions could be cleaned out.

**Comment by Gustry** [comment]
Hi,

Thanks for this work.

> It would need more work if you wanted it to still work in 2.x, otherwise ideally all the code that was to support older versions could be cleaned out.

The QGIS minimum version in the metadata.txt has been raised to 3.0, so it's fine to remove old code. I saw you kept some code for 1.8. Feel free to remove it if you want, but it's not compulsory ;-) I will review tomorrow the other part.

**Comment by Gustry** [comment]
@AlisterH How do you feel about this PR? Is-it ready for a review?

**Comment by AlisterH** [comment]
Yes please - I'm not doing anything else to it.

**Comment by Gustry** [comment]
Ok, I will take of the plugin for QGIS 3 now. Thanks!

**Pull request merged**
